# Generated by Django 5.2.5 on 2026-02-24 12:33

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(help_text='Course code (e.g., CS101)', max_length=10, unique=True)),
                ('title', models.CharField(help_text='Course title', max_length=200)),
                ('description', models.TextField(blank=True, help_text='Course description')),
                ('credit_units', models.PositiveIntegerField(default=3, help_text='Credit units for this course', validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(12)])),
                ('capacity', models.PositiveIntegerField(default=100, help_text='Maximum number of students', validators=[django.core.validators.MinValueValidator(1)])),
                ('semester', models.PositiveIntegerField(choices=[(1, 'Semester 1'), (2, 'Semester 2'), (3, 'Semester 3'), (4, 'Semester 4'), (5, 'Semester 5'), (6, 'Semester 6')], default=1, help_text='Semester in which course is offered')),
                ('is_active', models.BooleanField(default=True, help_text='Whether course is currently active')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Course',
                'verbose_name_plural': 'Courses',
                'db_table': 'courses',
                'ordering': ['code'],
            },
        ),
        migrations.CreateModel(
            name='Programme',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Full programme name', max_length=200, unique=True)),
                ('code', models.CharField(help_text='Short programme code (e.g., BCS, DIT)', max_length=10, unique=True)),
                ('duration_years', models.PositiveIntegerField(choices=[(1, '1 Year'), (2, '2 Years'), (3, '3 Years'), (4, '4 Years'), (5, '5 Years'), (6, '6 Years')], default=3, help_text='Programme duration in years')),
                ('description', models.TextField(blank=True, help_text='Programme description and details')),
                ('department', models.CharField(blank=True, help_text='Department offering the programme', max_length=100)),
                ('is_active', models.BooleanField(default=True, help_text='Whether programme is currently active')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Programme',
                'verbose_name_plural': 'Programmes',
                'db_table': 'programmes',
                'ordering': ['code'],
            },
        ),
        migrations.CreateModel(
            name='Semester',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.PositiveIntegerField(help_text='Academic year', validators=[django.core.validators.MinValueValidator(2020), django.core.validators.MaxValueValidator(2050)])),
                ('term', models.PositiveIntegerField(choices=[(1, 'Semester 1'), (2, 'Semester 2'), (3, 'Semester 3 (Summer)')], help_text='Term number within the year')),
                ('is_active', models.BooleanField(default=False, help_text='Current active semester for registrations')),
                ('registration_start', models.DateField(blank=True, help_text='Course registration start date', null=True)),
                ('registration_end', models.DateField(blank=True, help_text='Course registration end date', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Semester',
                'verbose_name_plural': 'Semesters',
                'db_table': 'semesters',
                'ordering': ['-year', '-term'],
            },
        ),
    ]
