# Generated by Django 5.2.5 on 2026-02-24 12:33

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('academics', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='lecturer',
            field=models.ForeignKey(blank=True, help_text='Assigned lecturer', limit_choices_to={'role': 'LECTURER'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='taught_courses', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='course',
            name='prerequisites',
            field=models.ManyToManyField(blank=True, help_text='Courses that must be completed before taking this one', related_name='prerequisite_for', to='academics.course'),
        ),
        migrations.AddField(
            model_name='course',
            name='programme',
            field=models.ForeignKey(help_text='Programme this course belongs to', on_delete=django.db.models.deletion.CASCADE, related_name='courses', to='academics.programme'),
        ),
        migrations.AlterUniqueTogether(
            name='semester',
            unique_together={('year', 'term')},
        ),
    ]
