# Generated by Django 5.2.5 on 2026-02-24 12:33

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('academics', '0001_initial'),
        ('accounts', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Enrollment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('APPROVED', 'Approved'), ('DROPPED', 'Dropped'), ('REJECTED', 'Rejected')], default='PENDING', help_text='Enrollment status', max_length=20)),
                ('grade', models.CharField(blank=True, choices=[('A', 'A - Excellent'), ('B', 'B - Very Good'), ('C', 'C - Good'), ('D', 'D - Pass'), ('F', 'F - Fail'), ('P', 'P - Pass (Pass/Fail)'), ('I', 'I - Incomplete'), ('W', 'W - Withdrawn')], help_text='Final grade (if completed)', max_length=2, null=True)),
                ('date_registered', models.DateTimeField(auto_now_add=True, help_text='When enrollment was requested')),
                ('date_approved', models.DateTimeField(blank=True, help_text='When enrollment was approved', null=True)),
                ('date_dropped', models.DateTimeField(blank=True, help_text='When enrollment was dropped', null=True)),
                ('notes', models.TextField(blank=True, help_text='Additional notes (rejection reason, etc.)')),
                ('approved_by', models.ForeignKey(blank=True, help_text='Admin who approved this enrollment', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_enrollments', to=settings.AUTH_USER_MODEL)),
                ('course', models.ForeignKey(help_text='Course being enrolled in', on_delete=django.db.models.deletion.CASCADE, related_name='enrollments', to='academics.course')),
                ('semester', models.ForeignKey(help_text='Semester of enrollment', on_delete=django.db.models.deletion.CASCADE, related_name='enrollments', to='academics.semester')),
                ('student', models.ForeignKey(help_text='Enrolled student', on_delete=django.db.models.deletion.CASCADE, related_name='enrollments', to='accounts.studentprofile')),
            ],
            options={
                'verbose_name': 'Enrollment',
                'verbose_name_plural': 'Enrollments',
                'db_table': 'enrollments',
                'ordering': ['-date_registered'],
                'constraints': [models.UniqueConstraint(fields=('student', 'course', 'semester'), name='unique_enrollment')],
            },
        ),
    ]
